say_numbers_Random = ["1 Número del 1 al 10", "2 Tirar un dado", "3 Cualquier número aleatorio", "4 Elige un número impar al azar"]
do = ["how can you do", "how do you do"]
opciones = ["1 Reproducir vídeos en youtube", "2 Buscar en wikipedia", "3 Números aleatorios", "4 Generar una contraseña", "5 Jugar juegos", "6 traducir de español a inglés o viceversa"]
respTF = ["si", "no"]
adivina = []
word_User = []